server:
  port: 8000
  error:
    include-stacktrace: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG
    
spring:
  resources:
    static-locations: file:src/main/resources/static
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:jeldwen_beacon_export}?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
     database: MYSQL
     hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     show-sql: false
#     show-sql: true
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5InnoDBDialect
           globally_quoted_identifiers: true