apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: metallb
data:
  config: |
      address-pools:
      - addresses:
        - 127.0.0.1-127.0.0.1
        name: default
        protocol: layer2