server:
  port: 8000
  error:
    include-stacktrace: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  resources:
    static-locations: file:src/main/resources/static
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeldwenx?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
     database: MYSQL
     hibernate:
        ddl-auto: update
#     show-sql: false
     show-sql: true
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5InnoDBDialect
           globally_quoted_identifiers: true
